### EXECUTION SETTING ###
seed: 1
# The using GPU ID
cuda_id: 0
# The Running mode (train or test)
mode: test
# fine-tuning specify the ckpt dir name you want to load the model params.
# if you want to turn off the fine-tuning mode Set to .
finetune: False
# The state path which you want to resume the training
resume: False
# resume_dir: /home/david/Documents/bag_files/cvar_logs/good/ckpt_0627_1329_59_subway_ground/models/model_0076.pth
resume_dir: /home/david/Documents/bag_files/cvar_logs/good/ckpt_0627_1831_33_alldata_except_wells/models/model_0061.pth
# resume_dir: /home/david/Documents/bag_files/cvar_logs/good/ckpt_0628_2212_07_l1loss_alldata/models/model_0100.pth
# datasets: ["kymine", "mammoth", "subway_basement", "subway_ground", "valentine", "wells"]
# datasets: ["subway_ground"]
# datasets: ["subway_basement"]
datasets: ["mammoth"]
# datasets: ["valentine"]
# datasets: ["wells"]
# datasets: ["kymine"]

### TRAINING PARAMETERS ###
# the number of max iteration
max_epochs: 200000
# the batch size
batch_size: 1
train_val_test: [0.9, 0.05, 0.05]
validate_on_train: False

### DATA AUGMENTATION ###
augment_data: True

### NETWORK SETTING ###
in_channels: 9
out_channels: 2
img_size: 400
# UNet layer size
layer_size: 4
use_cvar_less_var: True

### LOSS PARAMETERS ###
hole_coef: 1.0
valid_coef: 1.0

use_cvar_loss: True
use_monotonic_loss: True
monotonic_loss_delta: 0.0001
loss_huber: 0.001
var_coef: 10.0
cvar_coef: 1.0
mono_coef: 1.0e-4

### OPTIMIZATION PARAMETERS ###
optim: Adam
initial_lr: 0.0005
finetune_lr: 0.0005
momentum: 0
weight_decay: 0
clip: False

### LOG INTERVALS ###
# viaulizing the output images
num_vis_imgs: 8
# saving the model, check if this validation loss has improved
save_model_loss: total
save_model_interval: 10
# printing the losses to standard output line
print_step_losses: False
show_progress_bar: True
alpha_test_val: [0.1,0.5,0.9]
alpha_stats_val: [0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95]
test_model_based: False

### DIRECTORY PATH ###
data_root: /home/david/Documents/bag_files/spot2_lasubway_collision/risk_dataset
ckpt_dir_root: /home/david/Documents/bag_files/spot2_lasubway_collision/risk_logs

