### EXECUTION SETTING ###
# The using GPU ID
cuda_id: 0
# The Running mode (train or test)
mode: train
# fine-tuning specify the ckpt dir name you want to load the model params.
# if you want to turn off the fine-tuning mode Set to .
finetune: False
# The state path which you want to resume the training
resume: False
resume_dir: /home/david/Documents/bag_files/cvar_logs/models/cvar_mono_model_0057.pth

### TRAINING PARAMETERS ###
# the number of max iteration
max_epochs: 200000
# the batch size
batch_size: 4

train_test_split: 1.0
train_val_split: 0.9

### DATA AUGMENTATION ###
alpha_random_variance: 15.0

### NETWORK SETTING ###
in_channels: 9
out_channels: 2
img_size: 400
# UNet layer size
layer_size: 4
use_cvar_less_var: True

### LOSS PARAMETERS ###
use_cvar_loss: True
use_monotonic_loss: True
monotonic_loss_delta: 0.001
loss_huber: 0.1
var_coef: 1.0
cvar_coef: 1.0
mono_coef: 1.0e-4

### OPTIMIZATION PARAMETERS ###
optim: Adam
initial_lr: 0.0002
finetune_lr: 0.0005
momentum: 0
weight_decay: 0

### LOG INTERVALS ###
# viaulizing the output images
num_vis_imgs: 8
# saving the model, check if this validation loss has improved
save_model_loss: total
save_model_interval: 10
# printing the losses to standard output line
print_step_losses: False
show_progress_bar: True
alpha_test_val: [0.1,0.5,0.9]
# alpha_test_val: [0.01,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.99]
alpha_scale_by_distance: 20.0

### DIRECTORY PATH ###
data_root: /home/david/Documents/bag_files/spot2_lasubway_collision/risk_dataset
ckpt_dir_root: /home/david/Documents/bag_files/spot2_lasubway_collision/risk_logs

